### PR TITLE
Fixing the ffmpeg build for Android

### PR DESCRIPTION
**Pull request by DroidPulkit**
Please let me know, if I have to send PR here at github or at gitlab, as I cannot fork at gitlab.

This is for Issue described here : https://github.com/BelledonneCommunications/linphone-android/issues/617

Edit :- I don't know how to change the git submodules head automatically in the https://gitlab.linphone.org/BC/public/linphone-sdk repo, I believe either it is done automatically or you need to change the .gitlab files?

@Viish Maybe you can take a look into this. Thank you.

### CODE REVIEW

**Comment by anders9ustafsson** [comment]
@DroidPulkit I cannot see any file changes in this PR. What code did your fix consist of?

**Comment by DroidPulkit** [comment]
> @DroidPulkit I cannot see any file changes in this PR. What code did your fix consist of?

Hi,
You can follow my comments here, and follow them, to generate the FFMPEG build.
https://gitlab.linphone.org/BC/public/linphone-sdk/issues/8#note_17831
Thanks,

**Comment by anders9ustafsson** [comment]
Many thanks, @DroidPulkit , and how stupid of me not to remember that I asked you the same question before on Gitlab 😄 

BTW, the changes you make to options_android.cmake, are those really necessary? Does it not suffice to disable Aaudio and Camera2 via the initial CMake configuration?

**Comment by anders9ustafsson** [comment]
@DroidPulkit I have successfully tried your fix now. I did not need to edit the *options_android.cmake* file, I could handle that issue by applying `-DENABLE_AAUDIO=NO -DENABLE_CAMERA2=NO` in the CMake configuration. 

I also needed to sync your *cmake_builder* branch with the latest on Belledonne's project, but otherwise building went smooth. Thanks again!

BTW, have you made any similar fixes for iOS? I have tested to build with FFMPEG enabled, but I get compilation errors on the ffmpeg library.

**Comment by DroidPulkit** [comment]
> Does it not suffice to disable Aaudio and Camera2 via the initial CMake configuration? 

Not sure, I didn't try that way.


> @DroidPulkit I have successfully tried your fix now. I did not need to edit the _options_android.cmake_ file, I could handle that issue by applying `-DENABLE_AAUDIO=NO -DENABLE_CAMERA2=NO` in the CMake configuration.
> 
> I also needed to sync your _cmake_builder_ branch with the latest on Belledonne's project, but otherwise building went smooth. Thanks again!
> 
> BTW, have you made any similar fixes for iOS? I have tested to build with FFMPEG enabled, but I get compilation errors on the ffmpeg library.

For iOS, I didn't build the project so far. Maybe, you can try hacking your way around with this cmake-builder file

**Pull request closed without merging**
